server:
  port: 8081
spring:
  application:
    name: jpa-teaoclock
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/h2;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect