server:
  port: 8082
spring:
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
  application:
    name: mongo-teaoclock
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      authentication-database: admin
      username: mongo-teaoclock-user
      password: 123
      uri: mongodb://localhost:27017/mongo-teaoclock
      auto-index-creation: true
eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
    instance:
    preferIpAddress: true