version: "3.8"

services:
  frontend-teaoclock:
    container_name: frontend-teaoclock
    build: .
    ports:
      - 3000:3000
    volumes:
      - "./:/app"
      - "/app/node_modules"
    stdin_open: true
    command: npm start
